services:
  - type: web
    name: ocr-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libtesseract-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
